
trigger:
- main

jobs:
- job: CI
  workspace:
    clean: all
    
  pool:
    name: nitsm-python-test

  steps:
  - script: pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: pip install .
    displayName: 'Install nitsm-python'

  - script: pytest tests systemtests --junitxml=test-results.xml --cov=nitsm --cov-report=xml
    displayName: 'Run python unit tests'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Publish test results'
    displayName: 'Display test results'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    displayName: 'Display code coverage results'
