# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint and 

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip black ni-python-styleguide setuptools wheel
    - name: Check code formatting with black
      run: |
        python -m black --check .
    - name: Lint with NI style guide
      run: |
        python -m ni_python_styleguide lint
#    - name: Install package in edit mode
#      run: |
#        pip install -e .
#    - name: Run unit tests
#      run: pytest
