# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip and install black
      run: |
        python -m pip install --upgrade pip black
    - name: Check code formatting with black
      run: |
        python -m black --check .
    - name: Install setuptools and wheel
      run: |
        python -m pip install --upgrade setuptools wheel      
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel
